"""Metadata introspection for the Demucs plugin used by cjm-ctl to generate the registration manifest.

Docs: https://cj-mills.github.io/cjm-media-plugin-demucsmeta.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/meta.ipynb.

# %% auto #0
__all__ = ['get_plugin_metadata']

# %% ../nbs/meta.ipynb #exports-imports
import os
import sys
from typing import Any, Dict
from . import __version__

# %% ../nbs/meta.ipynb #get-plugin-metadata
def get_plugin_metadata() -> Dict[str, Any]:  # Plugin metadata for manifest generation
    """Return metadata required to register this plugin with the PluginManager."""
    # Fallback base path (current behavior for backward compatibility)
    base_path = os.path.dirname(os.path.dirname(sys.executable))
    
    # Use CJM config if available, else fallback to env-relative paths
    cjm_plugin_data_dir = os.environ.get("CJM_PLUGIN_DATA_DIR")
    
    # Plugin data directory
    plugin_name = "cjm-media-plugin-demucs"
    if cjm_plugin_data_dir:
        data_dir = os.path.join(cjm_plugin_data_dir, plugin_name)
    else:
        data_dir = os.path.join(base_path, "data")
    
    db_path = os.path.join(data_dir, "demucs_jobs.db")
    
    # Ensure data directory exists
    os.makedirs(data_dir, exist_ok=True)
    
    return {
        "name": plugin_name,
        "version": __version__,
        # T24: non-empty description required by the substrate validator (SG-6 / V1 gate).
        "description": "Demucs v4 audio source separation (vocals extraction) for isolating speech from background music/noise.",
        "type": "media-processing",
        "category": "media",
        "interface": "cjm_media_plugin_system.processing_interface.MediaProcessingPlugin",
        
        "module": "cjm_media_plugin_demucs.plugin",
        "class": "DemucsProcessingPlugin",
        
        # Critical: The absolute path to THIS environment's python
        "python_path": sys.executable,
        
        "db_path": db_path,
        
        # Phase 5a / CR-7 reframe: binary hard-facts only (quantitative amounts dropped, V12 gate).
        "resources": {
            "requires_gpu": True
        },
        
        # Track 19: CUDA_VISIBLE_DEVICES + TORCH_HOME (templated) are declared on the
        # plugin class via WORKER_ENV; the substrate resolves + injects them at spawn.
        "env_vars": {}
    }
