"""Demucs v4 audio source separation plugin — provides vocals extraction for removing background noise and music from speech audio.

Docs: https://cj-mills.github.io/cjm-media-plugin-demucsplugin.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/plugin.ipynb.

# %% auto #0
__all__ = ['DemucsPluginConfig', 'DemucsProcessingPlugin']

# %% ../nbs/plugin.ipynb #exports-imports
import logging
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, ClassVar

import torch
from fastcore.basics import patch

from cjm_media_plugin_system.processing_interface import MediaProcessingPlugin
from cjm_media_plugin_system.core import MediaMetadata
from cjm_media_plugin_system.storage import MediaProcessingStorage

from cjm_plugin_system.utils.hashing import hash_file
from cjm_plugin_system.utils.cache_paths import cache_dir_for_config
from cjm_plugin_system.core.interface import RELOAD_TRIGGER, plugin_action, collect_plugin_actions, EnvVarSpec
from cjm_plugin_system.core.errors import PluginInputError
from cjm_plugin_system.utils.validation import (
    dict_to_config, config_to_dict, dataclass_to_jsonschema,
    SCHEMA_TITLE, SCHEMA_DESC, SCHEMA_ENUM, SCHEMA_MIN, SCHEMA_MAX
)

# Shared torch helpers (cjm-torch-plugin-utils): release + CUDA-OOM typing + device resolution.
from cjm_torch_plugin_utils.memory import release_model
from cjm_torch_plugin_utils.oom import cuda_oom_to_plugin_resource_error
from cjm_torch_plugin_utils.device import resolve_torch_device

# %% ../nbs/plugin.ipynb #config-dataclass
@dataclass
class DemucsPluginConfig:
    """Configuration for the Demucs processing plugin."""
    
    model: str = field(
        default="htdemucs",
        metadata={
            SCHEMA_TITLE: "Model",
            RELOAD_TRIGGER: "model",  # CR-4: change triggers model reload
            SCHEMA_DESC: "Demucs model to use for separation.",
            SCHEMA_ENUM: ["htdemucs", "htdemucs_ft", "htdemucs_6s", "mdx_extra", "mdx_extra_q"]
        }
    )
    
    device: str = field(
        default="auto",
        metadata={
            SCHEMA_TITLE: "Device",
            RELOAD_TRIGGER: "model",  # CR-4: change triggers model reload
            SCHEMA_DESC: "Compute device. 'auto' selects CUDA if available.",
            SCHEMA_ENUM: ["auto", "cpu", "cuda"]
        }
    )
    
    shifts: int = field(
        default=1,
        metadata={
            SCHEMA_TITLE: "Shifts",
            SCHEMA_DESC: "Number of random shifts for prediction averaging. Higher = better quality but slower.",
            SCHEMA_MIN: 0, SCHEMA_MAX: 10
        }
    )
    
    overlap: float = field(
        default=0.25,
        metadata={
            SCHEMA_TITLE: "Overlap",
            SCHEMA_DESC: "Overlap between prediction windows (0.0 to 0.5).",
            SCHEMA_MIN: 0.0, SCHEMA_MAX: 0.5
        }
    )
    
    segment: Optional[int] = field(
        default=None,
        metadata={
            SCHEMA_TITLE: "Segment Length",
            SCHEMA_DESC: "Split audio into segments of this many seconds for processing. None = process whole file."
        }
    )
    
    save_other_stems: bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Save Other Stems",
            SCHEMA_DESC: "Also save drums, bass, and other stems alongside vocals."
        }
    )
    
    output_format: str = field(
        default="wav",
        metadata={
            SCHEMA_TITLE: "Output Format",
            SCHEMA_DESC: "Format for output audio files.",
            SCHEMA_ENUM: ["wav", "flac", "mp3"]
        }
    )

# %% ../nbs/plugin.ipynb #plugin-class
class DemucsProcessingPlugin(MediaProcessingPlugin):
    """Demucs v4 source separation plugin for vocals extraction."""
    
    config_class = DemucsPluginConfig

    # Track 19 (CR-12 worker-env model): worker spawn env declared on the class.
    # CUDA_VISIBLE_DEVICES is static; TORCH_HOME is templated to the substrate models
    # dir (Demucs downloads weights via torch.hub). The substrate injects at Popen.
    WORKER_ENV: ClassVar[List[EnvVarSpec]] = [
        EnvVarSpec(
            name="CUDA_VISIBLE_DEVICES",
            default="0",
            label="GPU Device",
            description="Which GPU index the worker uses.",
        ),
        EnvVarSpec(
            name="TORCH_HOME",
            default="${CJM_MODELS_DIR}/torch",
            label="Torch Hub Cache",
            description="torch.hub cache root for Demucs model downloads (templated to the substrate models dir).",
        ),
    ]
    
    def __init__(self):
        """Initialize the plugin."""
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")
        self.config: Optional[DemucsPluginConfig] = None
        self.storage: Optional[MediaProcessingStorage] = None
        self._data_dir: Optional[str] = None
        self._separator = None  # Lazy-loaded Demucs Separator
    
    # ── Properties ──────────────────────────────────────────────────
    
    @property
    def name(self) -> str:  # Plugin name identifier
        """Get the plugin name."""
        return "cjm-media-plugin-demucs"
    
    @property
    def version(self) -> str:  # Plugin version string
        """Get the plugin version."""
        from cjm_media_plugin_demucs import __version__
        return __version__
    
    @property
    def supported_media_types(self) -> List[str]:  # Supported media types
        """Get supported media types."""
        return ["audio"]
    
    # ── Lifecycle ────────────────────────────────────────────────────
    

    def initialize(self,
                   config: Optional[Any] = None,  # Configuration dict or None for defaults
                  ) -> None:
        """First-time setup. CR-4: config application factored into _apply_config; the
        substrate's reconfigure path fires _release_model on a model/device change then
        re-applies config."""
        self._apply_config(config)
        
        from .meta import get_plugin_metadata
        metadata = get_plugin_metadata()
        db_path = metadata["db_path"]
        self._data_dir = str(Path(db_path).parent)
        
        self.storage = MediaProcessingStorage(db_path)
        self.logger.info(f"Initialized with model={self.config.model}, "
                         f"device={self.config.device}")
    


    
    
    def get_config_schema(self) -> Dict[str, Any]:  # JSON Schema for UI forms
        """Return JSON Schema for the plugin configuration."""
        return dataclass_to_jsonschema(DemucsPluginConfig)
    
    def get_current_config(self) -> Dict[str, Any]:  # Current config as dict
        """Return the current configuration."""
        return config_to_dict(self.config) if self.config else {}
    
    # ── Model Management ────────────────────────────────────────────
    
    
    
    # ── Job Storage ──────────────────────────────────────────────────
    
    
    # ── Action Dispatch ──────────────────────────────────────────────
    
    def execute(self,
                action: str = "separate_vocals",  # Action to perform
                **kwargs
               ) -> Dict[str, Any]:  # Action result
        """Dispatch to the `@plugin_action`-tagged handler for `action` (SG-44)."""
        for klass in type(self).__mro__:
            for attr in vars(klass).values():
                if getattr(attr, "_plugin_action", None) == action:
                    return attr(self, **kwargs)
        raise PluginInputError(  # SG-47: typed input-validation
            f"Unknown action: {action}", fields_invalid=["action"],
        )


    
    # ── Interface Methods (not applicable) ───────────────────────────
    
    def get_info(self,
                 file_path: str,  # Path to audio file
                ) -> MediaMetadata:  # File metadata
        """Get basic audio file metadata via ffprobe."""
        from demucs.audio import AudioFile
        af = AudioFile(file_path)
        return MediaMetadata(
            path=file_path,
            format=Path(file_path).suffix.lstrip('.'),
            duration=af.duration,
            size_bytes=Path(file_path).stat().st_size,
            audio_streams=[{
                'channels': af.channels(),
                'sample_rate': af.samplerate(),
            }],
            video_streams=[],
        )
    
    def convert(self, input_path, output_format, **kwargs):
        """Not applicable for source separation."""
        raise PluginInputError(  # SG-47: typed input-validation; this method is
            # not applicable for this plugin domain.
            "convert is not supported by the Demucs plugin. "
            "Use 'separate_vocals' instead.",
            fields_invalid=["action"],
        )
    
    def extract_segment(self, input_path, start, end, output_path=None):
        """Not applicable for source separation."""
        raise PluginInputError(  # SG-47: typed input-validation; this method is
            # not applicable for this plugin domain.
            "extract_segment is not supported by the Demucs plugin. "
            "Use 'separate_vocals' instead.",
            fields_invalid=["action"],
        )
    
    # ── Core Action ──────────────────────────────────────────────────

# %% ../nbs/plugin.ipynb #m-apply-config
@patch
def _apply_config(self:DemucsProcessingPlugin,
                  config: Optional[Any] = None,  # Configuration dict or None for defaults
                 ) -> None:
    """CR-4: apply config values only. Called by initialize (first-time) and the
    substrate's reconfigure delta path. Model release on a model/device change is
    handled declaratively via RELOAD_TRIGGER -> _release_model (device resolved
    lazily in _load_model)."""
    self.config = dict_to_config(DemucsPluginConfig, config or {})

# %% ../nbs/plugin.ipynb #m-prefetch
@patch
def prefetch(self:DemucsProcessingPlugin) -> None:
    """CR-4 (SG-19): eagerly load the model so the first execute() doesn't pay
    the download/load cost. Idempotent via _load_model's None-guard."""
    self._load_model()

# %% ../nbs/plugin.ipynb #m-on-disable
@patch
def on_disable(self:DemucsProcessingPlugin) -> None:
    """CR-2: release the GPU model when the operator disables the plugin (the
    worker stays alive); lazy reload on the next execute after re-enable."""
    self._release_model()

# %% ../nbs/plugin.ipynb #m-cleanup
@patch
def cleanup(self:DemucsProcessingPlugin) -> None:
    """Clean up plugin resources."""
    self._release_model()
    self.logger.info("Plugin cleaned up")

# %% ../nbs/plugin.ipynb #m-is-available
@patch
def is_available(self:DemucsProcessingPlugin) -> bool:  # Whether the plugin can run
    """Check if the plugin is available on this system."""
    try:
        import demucs  # noqa
        return True
    except ImportError:
        return False

# %% ../nbs/plugin.ipynb #m-load-model
@patch
def _load_model(self:DemucsProcessingPlugin) -> None:
    """Load the Demucs Separator (lazy, cached).

    CR-4: a model/device change releases the separator declaratively via
    RELOAD_TRIGGER -> _release_model, so no manual change-detection is needed here —
    a None separator means a (re)load is required. The heartbeat wraps the WHOLE
    load: Separator() downloads weights via torch.hub on a cold cache (silent to the
    substrate's stall detector), so the heartbeat keeps the (progress, message)
    tuple advancing to avoid a false-positive stall."""
    if self._separator is not None:
        return

    device = resolve_torch_device(self.config.device)
    self.logger.info(f"Loading Demucs model '{self.config.model}' on {device}...")
    from demucs.api import Separator
    with self.heartbeat("loading Demucs model"):
        self._separator = Separator(
            model=self.config.model,
            device=device,
            shifts=self.config.shifts,
            overlap=self.config.overlap,
            segment=self.config.segment,
        )
    self.logger.info(f"Model loaded: samplerate={self._separator.samplerate}")

# %% ../nbs/plugin.ipynb #m-release-model
@patch
def _release_model(self:DemucsProcessingPlugin) -> None:
    """CR-4: release the Demucs Separator + free CUDA cache. RELOAD_TRIGGER target
    for model/device; on_disable / cleanup delegate here. Idempotent via
    cjm-torch-plugin-utils' release_model (no-op when already released)."""
    release_model(self, ["_separator"], device="cuda", logger=self.logger)

# %% ../nbs/plugin.ipynb #m-store-job
@patch
def _store_job(self:DemucsProcessingPlugin,
               action: str,  # Action name
               input_path: str,  # Source file path
               output_path: str,  # Output file path
               parameters: Optional[Dict[str, Any]] = None,  # Action parameters
               metadata: Optional[Dict[str, Any]] = None,  # Additional metadata
               input_hash: Optional[str] = None,  # Pre-computed input hash
              ) -> str:  # Generated job_id
    """Hash input/output files and store a processing job record."""
    job_id = str(uuid.uuid4())
    if input_hash is None:
        input_hash = hash_file(input_path)
    output_hash = hash_file(output_path)
    self.storage.save(
        job_id=job_id, action=action,
        input_path=input_path, input_hash=input_hash,
        output_path=output_path, output_hash=output_hash,
        parameters=parameters, metadata=metadata
    )
    return job_id

# %% ../nbs/plugin.ipynb #m-action-get-info
@patch
@plugin_action("get_info")
def _action_get_info(self:DemucsProcessingPlugin, **kwargs) -> Dict[str, Any]:
    """Action wrapper -> get_info()."""
    return self.get_info(kwargs["file_path"]).to_dict()

# %% ../nbs/plugin.ipynb #m-action-separate-vocals
@patch
@plugin_action("separate_vocals")
def _action_separate_vocals(self:DemucsProcessingPlugin, **kwargs) -> Dict[str, Any]:
    """Action wrapper -> _separate_vocals()."""
    return self._separate_vocals(**kwargs)

# %% ../nbs/plugin.ipynb #m-separate-vocals
@patch
def _separate_vocals(self:DemucsProcessingPlugin,
                     input_path: str,  # Path to audio file
                     output_dir: Optional[str] = None,  # Output directory (default: content+config cache dir)
                     output_format: Optional[str] = None,  # Output format override
                    ) -> Dict[str, Any]:  # Separation result
    """Extract vocals stem from an audio file."""
    fmt = output_format or self.config.output_format
    input_p = Path(input_path)

    # Determine output directory. Q3 Layer B: a content+config-addressed cache dir
    # (<data_dir>/separate_vocals/<stem>/<input6>_<config12>/) so a re-run with a
    # different model/format lands in a DISTINCT dir instead of overwriting — and a
    # chained upstream change invalidates this key automatically.
    if output_dir is None:
        out_dir = cache_dir_for_config(
            self._data_dir, input_path, "separate_vocals", config_to_dict(self.config),
        )
    else:
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

    # Load model (lazy, cached)
    self.report_progress(0.0, "Loading model...")
    self._load_model()

    # Run separation. SG-47 Track B wraps the inference site so CUDA OOM surfaces as
    # PluginResourceError (via cjm-torch-plugin-utils) → CR-7 reactive-retry reloads.
    self.report_progress(0.1, "Separating audio...")
    try:
        origin, separated = self._separator.separate_audio_file(input_p)
    except torch.cuda.OutOfMemoryError as e:
        raise cuda_oom_to_plugin_resource_error(
            e, label=f"during Demucs separation (model={self.config.model!r})",
        ) from e

    # Save vocals
    self.report_progress(0.8, "Saving vocals...")
    from demucs.audio import save_audio
    vocals_path = out_dir / f"vocals.{fmt}"
    save_audio(separated["vocals"], str(vocals_path),
               samplerate=self._separator.samplerate)

    # Optionally save other stems
    other_stems_saved = []
    if self.config.save_other_stems:
        for stem_name, stem_tensor in separated.items():
            if stem_name == "vocals":
                continue
            stem_path = out_dir / f"{stem_name}.{fmt}"
            save_audio(stem_tensor, str(stem_path),
                       samplerate=self._separator.samplerate)
            other_stems_saved.append(str(stem_path))

    # Hash and store job
    self.report_progress(0.9, "Storing job record...")
    job_id = self._store_job(
        action="separate_vocals",
        input_path=str(input_p),
        output_path=str(vocals_path),
        parameters={
            "model": self.config.model,
            "output_format": fmt,
            "shifts": self.config.shifts,
            "overlap": self.config.overlap,
        },
        metadata={
            "duration": float(separated["vocals"].shape[-1]) / self._separator.samplerate,
            "stems": list(separated.keys()),
            "device": str(self.config.device),
            "other_stems_saved": other_stems_saved,
        },
    )

    self.report_progress(1.0, "Complete")

    return {
        "job_id": job_id,
        "output_path": str(vocals_path),
        "input_path": str(input_p),
        "duration": float(separated["vocals"].shape[-1]) / self._separator.samplerate,
        "model": self.config.model,
        "stems_available": list(separated.keys()),
    }

# %% ../nbs/plugin.ipynb #plugin-class-tail
DemucsProcessingPlugin.supported_actions = collect_plugin_actions(DemucsProcessingPlugin)
